'use client'
import { Header } from '@/components/header/header'
import './styles/global.scss'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import { Scrollbar } from '@/components/scrollbar'
import { Lenis } from '@studio-freight/react-lenis'

const inter = Inter({ subsets: ['latin'] })
const N27 = localFont({ src: '../font/n27.woff' }) // виправлений шлях

export const metadata = {
  title: 'V\’nB Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={N27.className}>
      <Lenis root>
        <Scrollbar />
        <Header />
        {children}
        </Lenis>
      </body>
    </html>
  )
}
